import 'dotenv/config';

const {
  DISCORD_GUILD_ID,
  SCOUT_BOT_TOKEN,
  SCOUT_CLIENT_ID,
  SPARK_BOT_TOKEN,
  SPARK_CLIENT_ID,
  FORGE_BOT_TOKEN,
  FORGE_CLIENT_ID,
  MIRROR_BOT_TOKEN,
  MIRROR_CLIENT_ID,
  COORDINATOR_BOT_TOKEN,
  COORDINATOR_CLIENT_ID,
  GROQ_API_KEY,
  TAVILY_API_KEY,
  NOTION_KEY,
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  TASK_ADMIN_ROLE_ID,
} = process.env;

if (
  !DISCORD_GUILD_ID ||
  !SCOUT_BOT_TOKEN ||
  !SCOUT_CLIENT_ID ||
  !SPARK_BOT_TOKEN ||
  !SPARK_CLIENT_ID ||
  !FORGE_BOT_TOKEN ||
  !FORGE_CLIENT_ID ||
  !MIRROR_BOT_TOKEN ||
  !MIRROR_CLIENT_ID ||
  !COORDINATOR_BOT_TOKEN ||
  !COORDINATOR_CLIENT_ID ||
  !GROQ_API_KEY ||
  !TAVILY_API_KEY ||
  !NOTION_KEY ||
  !SUPABASE_URL ||
  !SUPABASE_ANON_KEY
) {
  console.error('Missing required env vars.');
  process.exit(1);
}

export {
  DISCORD_GUILD_ID,
  SCOUT_BOT_TOKEN,
  SCOUT_CLIENT_ID,
  SPARK_BOT_TOKEN,
  SPARK_CLIENT_ID,
  FORGE_BOT_TOKEN,
  FORGE_CLIENT_ID,
  MIRROR_BOT_TOKEN,
  MIRROR_CLIENT_ID,
  COORDINATOR_BOT_TOKEN,
  COORDINATOR_CLIENT_ID,
  GROQ_API_KEY,
  TAVILY_API_KEY,
  NOTION_KEY,
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  TASK_ADMIN_ROLE_ID,
};
